/-
Copyright (c) 2026 DstDiophantine contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: DstDiophantine contributors
-/

import DstDiophantine.Algebra.Admissible
import DstDiophantine.Algebra.Amplification
import DstDiophantine.Algebra.Cl31
import DstDiophantine.Algebra.Continuum
import DstDiophantine.Algebra.Discrete
import DstDiophantine.Algebra.Generators
import DstDiophantine.Algebra.Invariant
import DstDiophantine.Algebra.ModularAmplification
import DstDiophantine.Algebra.Motor
import DstDiophantine.Algebra.Operations
import DstDiophantine.Algebra.PGA
import DstDiophantine.Algebra.QuadraticForm
import DstDiophantine.Algebra.Sandwich
import DstDiophantine.Algebra.UnitGroup

/-!
# DST algebraic core barrel

Re-exports the PGA / biquaternion / discrete-torus layer used by the main paper
and the discrete companion. Diophantine theorems and Gravity chart modules are
**not** imported here.
-/

namespace DstDiophantine

export PGA (ι e4Index e4_sq_zero e4_anticomm e4_inner_anticomm)
export Cl31 (ι toPGA toPGA_ι)
export Generators (hyperbolic cyclic null null_sq null_mul_null hyperbolic_sq cyclic_sq
  commutator commutator_null_null null_commute
  commutator_hyperbolic_cyclic_same commutator_hyperbolic0_cyclic1_ne_zero)
export Operations (pseudoscalar dual TorsionParams daggerParams
  e4_commute_pseudoscalar dual_null
  pseudoscalar_sq ι_anticomm_pseudoscalar minkowskiVector minkowskiVector_sq
  Q31_eq_minkowskiDot minkowskiVector_anticomm_pseudoscalar
  dual_minkowskiVector_sq dual_time)
export Admissible (IsPrincipalBranch IsAdmissibleContinuous
  admissibleContinuous_implies_principalBranch)
export Discrete (DiscreteTorsion toTorsionParams IsAdmissible
  toTorsionParams_alpha_nonneg toTorsionParams_beta_nonneg
  isAdmissible_iff_admissibleContinuous isAdmissible_iff_principalBranch
  admissible_continuous_of_discrete admissible_sum_le admissible_alpha_le_half_pi
  admissible_beta_le_half_pi)
export Motor (TransParams OmegaParams omegaTorsion omegaTrans omegaBiv expTrans rotorTorsion motor
  omegaTrans_sq omegaTorsion_reverse expTrans_unitary rotor_unitary motor_unitary
  reverse_mul_of_mul_reverse exp_of_sq_one exp_of_sq_neg_one)
export Sandwich (sandwich sandwich_one sandwich_smul sandwich_add sandwich_comp sandwich_reverse
  sandwich_mul sandwich_sq sandwich_minkowskiVector_sq
  rotorTorsion_pureBoost_closed sandwich_pureBoost_ι0 sandwich_pureBoost_ι1
  sandwich_pureBoost_ι2 sandwich_pureBoost_lightlike_plus sandwich_pureBoost_lightlike_minus
  rotorTorsion_pureRotation_closed)
export UnitGroup (discreteRotor DiscreteUnit DiscreteRotorImage discreteUnit_finite
  discreteRotorImage_finite reverse_discreteRotor discreteRotor_mul_reverse
  negTorsionParams)
export Invariant (J J5 JNormalized counterExampleParams J_coef JNormalized_coef J5_eq killingForm
  omegaTorsionGeneratorKilling omegaTorsionGeneratorKilling_eq
  omegaTorsion_killing_vs_param paper_appendix_killing_coeff_false
  one_sixteenth_omegaKilling_eq J_eq_four_times_one_sixteenth_omegaKilling
  axis_sq_diff_eq sq_diff_le_half_pi_sq sq_diff_eq_half_pi_sq_iff
  euclideanForm mass massNormalized mass_coef mass_nonneg mass_eq_zero_iff
  J_eq_zero_of_mass_eq_zero mass_dagger massNormalized_coef massNormalized_nonneg
  massNormalized_eq_zero_iff JNormalized_eq_zero_of_massNormalized_eq_zero
  sq_sum_le_half_pi_sq sq_sum_eq_half_pi_sq_iff
  mass_bound_raw_continuous massNormalized_bound_continuous
  balancedRay JNormalized_balancedRay mass_balancedRay massNormalized_balancedRay
  mass_balancedRay_pos isAdmissibleContinuous_balancedRay
  not_admissible_balancedRay_of_one_lt JNormalized_zero_not_implies_vacuum
  IsPureHyperbolic IsPureElliptic
  IsSpatialTrans IsBoundedTrans J5_unbounded J5_bound_spatial
  torsion_bound_raw torsion_bound_raw_continuous_pi_sq torsion_bound_raw_pi_sq
  torsion_bound torsion_bound_continuous JNormalized_extremal JNormalized_extremal_neg
  abs_JNormalized_eq_one_iff exists_admissible_JNormalized
  torsion_bound_naive_false)
export Amplification (scaleTorsion pureBoost pureBoost_scale_real pureBoost_scale
  J_scale JNormalized_scale mass_scale massNormalized_scale scaleTorsion_balancedRay
  J_pureBoost JNormalized_pureBoost JNormalized_pureBoost_nonneg
  J_pow_amplify JNormalized_pow_amplify rotorTorsion_pureBoost_pow
  isAdmissibleContinuous_pureBoost_iff)
export ModularAmplification (windingCoord amplifyDiscrete windingTotal amplifiedParams
  ModularAmplificationWitness modularWitness_example
  modularWitness_of_pureBoost modularWitness_of_pureBoost_winding
  modularWitness_four_le modularWitness_empty_of_lt_four modularWitness_empty_of_eq_three
  latticeMismatch_pureBoost latticeMismatch_ne_zero_of_winding_pureBoost
  isAdmissible_of_pureBoost_n0_le isAdmissible_amplifyDiscrete_of_pureBoost_smul_n0
  mul_val_eq_val_add_winding scale_angle_eq_mod_plus_winding
  J_scale_eq_J_amplified_add_error JNormalized_scale_eq_JNormalized_amplified_add_error
  windingCoord_lt windingCoord_pos_iff
  admissible_scale_implies_windingTotal_eq_zero
  windingTotal_ne_zero_implies_not_admissible_scale
  ModularAmplificationWitness.not_admissible_real_scale
  ConformalGaugeAdmissible IsPureBoostSeed
  windingTotal_pureBoost windingTotal_pureBoost_ne_zero_iff
  pureBoostSeedOfRapidity pureBoostSeedOfRapidity_isPureBoost
  quantizeRapidity_of_lt_two_pi windingTotal_ne_zero_of_rapidity_ge
  windingTotal_eq_zero_of_rapidity_lt
  not_exists_modularWitness_of_rapidity_lt
  not_exists_modularWitness_of_balanced_gap)
export Continuum (AdmissibleContinuous exists_discrete_approx exists_discrete_approx_J
  lattice_in_interval dense_discrete_JNormalized)

end DstDiophantine
