import DstDiophantine.Algebra
import DstDiophantine.Embedding.Equation
import DstDiophantine.Embedding.Height
import DstDiophantine.Embedding.IntegerRotor
import DstDiophantine.Embedding.NullTranslator
import DstDiophantine.Embedding.PowerMap
import DstDiophantine.Embedding.RotorClass
import DstDiophantine.Framework.Amplification
import DstDiophantine.Framework.Descent
import DstDiophantine.Framework.Lattice
import DstDiophantine.Framework.DiscreteCount
import DstDiophantine.Framework.Spectrum
import DstDiophantine.Framework.SpectrumSearch
import DstDiophantine.Framework.Representation
import DstDiophantine.Framework.Search
import DstDiophantine.Theorems.Fermat
import DstDiophantine.Theorems.FermatMixed
import DstDiophantine.Embedding.FermatMotor
import DstDiophantine.Theorems.Beal
import DstDiophantine.Theorems.BealSlice
import DstDiophantine.Theorems.BealPythagorean
import DstDiophantine.Theorems.BealGaussian
import DstDiophantine.Theorems.BealMixed
import DstDiophantine.Theorems.BealEven
import DstDiophantine.Theorems.BealGaussianCube
import DstDiophantine.Theorems.BealFinite
import DstDiophantine.Theorems.BealResidualSearch
import DstDiophantine.Theorems.DarmonMerel
import DstDiophantine.Theorems.FermatNN5
import DstDiophantine.Theorems.FermatLast
import DstDiophantine.Theorems.Collatz
import DstDiophantine.Theorems.Goldbach
import DstDiophantine.Theorems.Polignac
import DstDiophantine.Theorems.Abc
import DstDiophantine.Theorems.Riemann
import DstDiophantine.FoundationRegression

/-!
Core re-exports for the PGA / biquaternion algebra layer and the shared
amplification proof core (phases 1–6).

Algebraic DST primitives are re-exported via `DstDiophantine.Algebra`.
The PGA–TEGR chart layer lives in `DstDiophantine.Gravity` and is **not**
re-exported here, so the Diophantine path does not depend on gravity modules.
-/

namespace DstDiophantine

export Embedding (integerRotor integerRotor_mul integerRotor_pow nullTranslator nullTranslator_add
  nullTranslator_faithful translateBy logMismatch J_pow_amplify_int RotorClass integerClass
  quantizeInt quantizeMismatch quantizeRapidity principalRapidity
  quantizeInt_one quantizeInt_pureBoost
  quantizeMismatch_pureBoost quantizeRapidity_error quantizeMismatch_error
  quantizeRapidity_zmod_eq_principal principalRapidity_nonneg principalRapidity_lt_two_pi
  conformalPoint conformalInteger conformalPoint_sq conformalInteger_sq
  IsCGAIntegerPoint IsCGAIntegerPoint_conformalInteger IsCGAIntegerPoint_natAbs
  IsCGAPowerLatticePoint isCGAPowerLatticePoint_two_rpow_four_thirds
  IsCGAIntegerDilation IsCGAIntegerDilation_int IsCGAIntegerDilation_one
  IsCGAIntegerDilation_mul IsCGAIntegerPoint_cgaDilation
  IsCGAPowerLatticePoint_cgaDilation IsCGAIntegerDilation_div_iff
  not_isCGAIntegerDilation_five_div_three
  bilin21_conformalPoint_conformalPoint cgaDilationMismatch cgaDilationMismatch_eq
  conformalPoint_dilation_injective conformalPoint_dilation_not_two_pi_periodic
  bilin21_conformalPoint_nInf not_isCGAIntegerPoint_two_rpow_four_thirds
  torsionHeight integerHeight descentCandidate diophantineMotor
  additive_faithful diophantine_zero_iff)
export Framework (PowerSumEquation evalPowerSum powerSumMotor powerSumMotor_one_iff
  fermatEquation fermatMotor_one_iff bealEquation bealMotor_one_iff
  goldbachEquation goldbachMotor_one_iff abcEquation abcMotor_one_iff
  gapEquation gapMotor_one_iff
  IsZeroHeight AdmissibleClass ExistsZeroHeight
  latticeMismatch latticeMass abs_latticeMismatch_le_of_admissible
  latticeMass_le_of_admissible
  JNormalized_eq_sixteen_lattice massNormalized_eq_sixteen_lattice
  torsion_bound_discrete_sharp torsion_bound_discrete_sharp_le_one
  torsion_bound_discrete_strict massNormalized_discrete_sharp
  massNormalized_discrete_le_one
  admissible_eq_zero_of_lt_four JNormalized_eq_zero_of_lt_four
  exists_admissible_balanced_massive
  AxisPair triangleNum card_axisPair card_admissibleClass
  card_admissibleClass_eq_of_div_four card_admissibleClass_one_of_lt_four
  card_admissibleClass_four card_admissibleClass_eight
  axisMismatch axisMass axisMismatchSet threeMismatchSet mismatchHoles
  mismatchInterval
  one_mem_axisMismatchSet_iff neg_one_mem_axisMismatchSet_iff
  threeMismatchSet_subset_interval abs_three_axis_eq_ceiling_iff
  card_balancedTriples card_zeroHeight_gt_balanced
  abs_latticeMismatch_le_latticeMass latticeMismatch_modEq_latticeMass
  latticeMass_eq_zero_iff latticeMismatch_mem_threeMismatchSet
  exists_admissible_mismatch_one exists_admissible_mismatch_neg_one
  torsion_gap_attained exists_unbalanced_zeroHeight_massive
  JNormalized_eq_sharp_iff abs_latticeMismatch_eq_ceiling_iff
  axisMismatchSet_two threeMismatchSet_one mismatchHoles_two
  ten_not_mem_threeMismatchSet_two mismatchHoles_three
  threeMismatchSet_proper_subset_interval_two
  zeroHeight_card_one zeroHeight_card_two zeroHeight_card_three
  pureHyperbolicDiscrete pureEllipticDiscrete
  pureHyperbolicDiscrete_admissible pureEllipticDiscrete_admissible
  JNormalized_pureHyperbolicDiscrete JNormalized_pureEllipticDiscrete
  dagger_preserves_height DescentSchema latticeSearchSchema
  findZeroHeight findZeroHeight_isSome phase4_layers
  amplification_implies_seed_le continuous_amplification_contradiction
  abs_latticeMismatch_ge_one discrete_nonzero_height_lb
  discrete_amplification_contradiction
  coarse_height_gap coarse_condition_of_le_two_mul
  coarse_height_gap_of_le_two_mul coarse_discrete_contradiction
  CoarseAmplificationWitness coarse_implies_lt_four_mul
  scale_admissible_iff_four_mul_le)
export Theorems (fermat_solution_iff_motor fermat_pos_lt mismatchRotor_eq_rotorTorsion
  fermat_balanced_seed_constant_lt_one fermat_balanced_seed_height_eq
  fermat_balanced_seed_lt_threshold fermat_balanced_amplification_admissible
  fermat_amplification_contradiction
  fermat_coarse_height_gap fermat_coarse_condition_of_le_two_mul
  fermat_coarse_height_gap_of_le_two_mul fermat_coarse_discrete_contradiction
  FermatAdmissibleBridge fermat_last_theorem_of_bridge
  FermatCoarseDiscreteBridge
  fermat_last_theorem_of_coarse_discrete_bridge
  FermatModularBridge fermat_last_theorem_of_modular_bridge
  FermatLastTheorem_of_modular_bridge
  fermat_larger_base_log_le fermat_larger_base_no_modularWitness
  fermat_larger_base_windingTotal_eq_zero
  FermatMixedMotorResidual fermat_pos_of_mixed_motor_residual
  FermatLastTheorem_of_mixed_motor_residual
  isMixedFermatMotor_of_sol fermatBoost_eq_zero_iff_pythagorean
  beal_solution_iff_motor bealMinExp bealAmpExp bealExpGcd bealGcd
  beal_amplification_contradiction
  beal_discrete_amplification_contradiction BealAdmissibleBridge
  beal_conjecture_of_bridge beal_eq_exp_not_coprime_of_bridge
  bealFracLogGap bealFracLogGap_mul bealFracLogGap_of_solution bealFracLogGap_eq_exp
  bealFracLogGap_eq_log_one_add_div bealFracLogGap_pos_of_solution
  beal_winding_threshold_gt_half_pi_of_minExp_eq_three
  beal_balanced_fracGap_lt_winding_threshold beal_balanced_fracGap_lt_ampExp_threshold
  beal_pos_pow_lt beal_balanced_seed_lt_threshold
  quantizeBealMismatch quantizeBealMismatch_pureBoost
  BealModularBridge beal_modular_payload_incompatible
  beal_conjecture_of_modular_bridge
  beal_eq_exp_not_coprime_of_modular_bridge beal_has_winding_of_fracGap_ge
  BealWindingBridge bealRootMag bealRootMag_pos bealRootMag_pow bealRootMag_eq_natAbs
  bealRootMag_isCGAPowerLatticePoint
  bealFracLogGap_eq_log_rootMag beal_rootMag_pow_sum_of_solution
  beal_pairwise_coprime beal_coprime_ac beal_coprime_ab beal_coprime_bc
  bealCGADilationMismatch bealCGADilationMismatch_pos_of_solution
  bealCGAKFoldMag bealCGAKFoldMag_eq_root_ratio bealCGAKFoldMag_pow
  beal_kFold_powerLattice_dvd beal_natAbs_eq_one_of_ac_pow_dvd
  beal_natAbs_eq_one_of_kFold_powerLattice
  beal_kFold_powerLattice_of_natAbs_eq_one beal_kFold_powerLattice_iff_natAbs_eq_one
  bealGcd_eq_one_of_not_gt beal_balanced_gap_no_modularWitness
  BealCGAGauge BealCGAGauge_of_ne_zero beal_cga_dilation_weights
  BealCGALatticeGauge BealCGALatticeGauge_of_eq_exp beal_eq_exp_lattice_fermat_form
  BealCGANoGo BealCGADilationNoGo BealCGADiscreteClosed BealUnitBaseNoGo
  BealCGADiscreteClosed_iff_unitAbs
  bealUnitBaseNoGo_pos beal_conjecture_pos_of_discreteClosed
  IsDSTBealDiscreteConfig BealCGARealization
  beal_integerDilation_iff_pow_eq beal_integerDilation_of_coprime_iff
  beal_eq_exp_integerDilation_iff_natAbs_eq_one
  not_beal_eq_exp_integerDilation_three_four_five
  beal_natAbs_eq_one_of_dstDiscreteConfig not_dstDiscreteConfig_coprime_pos
  IsDSTBealDiscreteConfig_of_realization beal_conjecture_pos_of_realization
  beal_eq_exp_mismatchRotor_scale beal_eq_exp_integerDilation_iff
  beal_eq_pow_mul_expGcd bealGcd_pow_eq_one
  beal_fermat_of_expGcd_ge_three not_beal_sol_of_expGcd_ge_three_of_FLT
  beal_conjecture_of_expGcd_ge_three_of_FLT beal_eq_exp_not_sol_of_FLT
  not_beal_sol_of_expGcd_ge_three_of_modular_bridge
  fermatLastTheorem not_beal_sol_of_expGcd_ge_three beal_conjecture_of_expGcd_ge_three
  bealExpGcd_eq_one_or_eq_two_or_ge_three bealExpGcd_eq_one_implies_not_all_eq
  bealExpGcd_eq_two_dvd bealExpGcd_div_two_eq_one
  beal_pythagorean_of_expGcd_eq_two beal_pythagoreanTriple_of_expGcd_eq_two
  beal_pythagorean_legs_coprime_of_expGcd_eq_two
  beal_pythagorean_classification_of_expGcd_eq_two
  BealMixedExpResidual beal_two_equal_exp_of_expGcd_eq_one
  beal_eq_two_exp_form_of_expGcd_eq_one
  beal_two_equal_exp_yz_of_expGcd_eq_one beal_eq_two_exp_yz_form_of_expGcd_eq_one
  beal_two_equal_exp_xz_of_expGcd_eq_one beal_eq_two_exp_xz_form_of_expGcd_eq_one
  beal_expGcd_eq_one_two_equal_or_all_distinct
  beal_all_distinct_exp_of_expGcd_eq_one
  nat_eq_pow_of_mul_eq_pow_of_coprime nat_eq_pow_of_mul_eq_pow_of_coprime_right
  exists_pow_of_two_mul_coprime_eq_pow exists_sq_of_two_mul_coprime_eq_sq
  gaussian_norm_mk IsGaussianHypotenusePower isGaussianHypotenusePower_one
  isGaussianHypotenusePower_of_hyp_eq_pow exists_associated_pow_of_hyp_eq_pow
  isCoprime_mk_star_of_coprime_opposite_parity
  beal_conjecture_pos_of_residuals
  BealEqualOddTwoFactorResidual BealTwoEqualEvenResidual
  BealTwoEqualOddResidual BealAllDistinctExpResidual
  BealPythagoreanUnequalOddResidual
  beal_mixed_exp_of_subresiduals beal_pythagorean_of_subresiduals
  beal_conjecture_pos_of_fine_residuals
  not_beal_sol_eq_odd_yz_of_two_factor not_beal_sol_eq_odd_xz_of_two_factor
  exists_gaussian_hyp_pow_of_two_equal_xy_even odd_of_even_coprime
  darmonMerelCube not_beal_two_equal_third_three_of_DM not_beal_two_equal_third_three
  not_beal_two_equal_first_three_odd not_beal_two_equal_second_three_odd
  not_beal_two_equal_cube_slice
  fermatSignatureNN5 not_beal_two_equal_third_five_even
  not_beal_two_equal_fifth_slice
  BealTwoEqualEvenSumResidual BealTwoEqualEvenDiffResidual
  beal_two_equal_even_of_sum_diff beal_conjecture_pos_of_fine_residuals_even_split
  beal_two_equal_even_sum_gaussian
  BealTwoEqualEvenSumResidual_of_outside_cube
  BealTwoEqualEvenSumExpFiveResidual_of_NN5
  BealTwoEqualEvenSumResidual_of_ge_seven
  exists_two_mul_pow_eq_signed_pow_add_opposite_parity
  two_mul_pow_eq_signed_pow_add_of_diff_sum_abs
  gaussian_cube_eq not_two_mul_odd_eq_cube eq_odd_two_factor_cube_even_slot
  not_eq_odd_two_factor_of_exp_three_abs_one not_eq_odd_two_factor_of_exp_three
  not_eq_odd_two_factor_of_exp_ge_three_abs_one not_eq_odd_two_factor_abs_one_of_associated
  BealPosCubeAddTwoCubeResidual BealEqualOddTwoFactorExpGeFiveResidual
  BealAffineCubeAddTwoResidual BealPosCubeAddTwoCubeResidual_of_affine
  BealMordellCubeAddTwoResidual BealAffineCubeAddTwoResidual_of_mordell
  BealPosCubeAddTwoCubeResidual_of_mordell
  affineCubeAddTwoToMordell mordell_of_affine_cube_add_two
  affineCubeAddTwoToMordell_neg_one_one
  exists_pos_cube_add_two_cube_of_two_factor
  BealEqualOddTwoFactorResidual_of_pos_cube_and_ge_five
  nat_cube_mod_seven nat_cube_mod_nine
  even_pow_sub_eq_mul beal_two_equal_even_diff_yz_progress
  beal_two_equal_even_diff_xz_progress
  int_gcd_pow_diff_sum_dvd_two nat_gcd_pow_diff_sum_dvd_two
  nat_gcd_pow_diff_sum_eq_one_of_opposite_parity
  nat_gcd_pow_diff_sum_eq_two_of_both_odd
  exists_padicValNat_two_eq_one_of_both_odd
  exists_natAbs_pow_of_mul_eq_pow_of_coprime_abs
  exists_signed_pow_of_natAbs_eq_pow
  exists_signed_pow_of_diff_sum_mul_eq_pow_opposite_parity
  diff_sum_mul_eq_pow_both_odd_gcd_padic
  exists_odd_parts_pow_of_mul_eq_pow_gcd_two
  exists_odd_pow_parts_of_diff_sum_mul_eq_pow_both_odd
  BealTwoEqualEvenDiffPerfectPowerResidual
  BealTwoEqualEvenDiffFactorResidual
  BealTwoEqualEvenDiffFactorResidual_of_perfect_power
  BealTwoEqualEvenDiffResidual_of_factor
  BealTwoEqualEvenSumExpFiveResidual BealTwoEqualEvenSumExpGeSevenResidual
  BealTwoEqualEvenSumResidual_of_five_ge_seven
  isCoprimeBeal hasCoprimeBealUpTo noCoprimeBealUpTo
  noCoprimeBealUpTo_sound beal_no_coprime_of_le_eight_five
  findCoprimeBealUpTo findCoprimeBealUpTo_sound findCoprimeBealUpTo_complete
  findNthRoot isNthPower findNthRoot_eq_some_of
  hasCoprimeBealPerfectPowerUpTo noCoprimeBealPerfectPowerUpTo
  noCoprimeBealPerfectPowerUpTo_sound
  beal_no_coprime_perfect_power_of_le_nineteen_six
  beal_no_coprime_perfect_power_of_le_twelve_six
  beal_no_coprime_perfect_power_of_le_thirteen_six
  beal_no_coprime_perfect_power_of_le_fourteen_six
  beal_no_coprime_perfect_power_of_le_fifteen_six
  beal_no_coprime_perfect_power_of_le_sixteen_six
  beal_no_coprime_perfect_power_of_le_seventeen_six
  findCoprimeBealPerfectPowerUpTo findCoprimeBealPerfectPowerUpTo_sound
  findCoprimeBealPerfectPowerUpTo_complete
  mem_beal_bases mem_beal_exps
  beal_known_noncoprime_three_six beal_known_noncoprime_two_two
  beal_known_noncoprime_seven_fourteen beal_known_noncoprime_two_five
  beal_known_noncoprime_is_perfect_power known_noncoprime_not_isCoprimeBeal
  isPosCubeAddTwoPrimitive hasPosCubeAddTwoPrimitiveUpTo noPosCubeAddTwoPrimitiveUpTo
  findPosCubeAddTwoPrimitiveUpTo findPosCubeAddTwoPrimitiveUpTo_sound
  no_pos_cube_add_two_primitive_of_le_eighty
  no_pos_cube_add_two_primitive_of_le_forty
  no_pos_cube_add_two_primitive_of_le_fifty
  no_pos_cube_add_two_primitive_of_le_sixty
  isOpenResidualExponents isOpenResidualBealPerfectPower
  hasOpenResidualBealPerfectPowerUpTo noOpenResidualBealPerfectPowerUpTo
  findOpenResidualBealPerfectPowerUpTo
  beal_no_open_residual_perfect_power_of_le_forty_six
  beal_no_open_residual_perfect_power_of_le_twenty_six
  beal_no_open_residual_perfect_power_of_le_twentyfive_six
  beal_no_open_residual_perfect_power_of_le_thirty_six
  not_both_odd_bases_of_expGcd_eq_two_of_eq_odd_yz
  not_beal_sol_of_expGcd_eq_two_of_eq_odd_yz
  not_beal_sol_of_expGcd_eq_two_of_eq_odd_xz
  beal_two_equal_xy_even_progress beal_two_equal_xy_even_C_odd
  DiffFourthSqPos not_diffFourthSqPos
  not_pow_four_sub_pow_four_eq_sq not_pow_four_add_sq_eq_pow_four
  not_beal_sol_of_expGcd_eq_two_of_four_dvd_xz
  not_beal_sol_of_expGcd_eq_two_of_four_dvd_yz
  not_beal_sol_of_expGcd_eq_two_of_two_four_dvd
  BealPythagoreanResidual beal_pythagorean_residual_iff_two_odd_reduced
  not_beal_sol_of_expGcd_dvd_FLT_for
  not_beal_sol_of_three_dvd_expGcd not_beal_sol_of_four_dvd_expGcd
  not_beal_sol_of_three_or_four_dvd_expGcd
  not_beal_eq_exp_three not_beal_eq_exp_four
  not_beal_sol_of_expGcd_eq_two_of_four_dvd_xy
  beal_conjecture_of_winding_and_cga_nogo
  beal_conjecture_of_winding_and_cga_dilation_nogo
  beal_eq_exp_not_coprime_of_winding_and_cga_dilation_nogo
  beal_conjecture_of_discreteClosed_and_unitBaseNoGo
  not_one_add_pow_three_eq_pow_three
  mihailescu not_unitAbs_pow_add_pow_eq_pow_pos
  beal_modularWitness_of_fracGap_window beal_modularWitness_of_fracGap_window_ampExp
  beal_modularWitness_of_principal_fracGap_window
  beal_winding_of_solution_window beal_winding_of_solution_principal_window
  beal_coprime_not_in_wide_window_of_cga_nogo
  exists_common_prime_of_bealGcd_gt_one
  collatzStep collatzIter ReachesOne collatzHeight collatzHeight_one
  collatzHeight_even_le collatz_odd_log_delta
  collatzHeight_le_one_implies_le_three IsCollatzCycle
  collatz_cycle_avoids_one_exceeds_bound eventually_periodic_of_fintype
  reachesOne_of_le_twenty CollatzAdmissibleBridge collatz_conjecture_of_bridge
  IsGoldbachPair goldbach_sum_iff_motor goldbach_solution_iff_motor
  goldbachTargetHeight goldbachTargetHeight_gt_one_of_four_le
  goldbachCandidates exists_min_goldbachMismatch
  goldbach_of_le_hundred GoldbachAdmissibleBridge goldbach_conjecture_of_bridge
  evenGap IsPolignacPair IsTwinPrimePair twin_prime_of_polignac
  polignac_gap_iff_motor even_gap_of_odd_prime_pair
  gapExcessTerm gapExcessSum gapChainHeight strong_avoidance_term_ge
  gapChainHeight_gt_one_of_sq exists_twin_of_le_twenty
  PolignacAdmissibleBridge polignac_conjecture_of_bridge
  twin_prime_conjecture_of_bridge
  abcRadical IsAbcTriple abcQuality abcMismatchParams abcHeight
  abcHeightCoef abcQualityCeiling discreteAbcCeiling
  abc_sum_iff_motor abc_solution_iff_motor abcHeight_eq_quality
  abc_quality_bound_of_admissible abc_amplification_contradiction
  abc_quality_gt_ceiling_not_admissible one_lt_abcQuality_iff
  abcMismatch_rapidity isAdmissibleContinuous_abcMismatch_iff
  discrete_abc_bound abc_radical_pow_of_le_hundred
  AbcAdmissibleBridge abc_conjecture_of_bridge AbcAdmissibleBridge_false
  quantizeAbcMismatch quantizeAbcMismatch_pureBoost abcLogGap
  AbcModularBridge abc_conjecture_of_modular_bridge
  abc_has_winding_of_logGap_ge isAbcTriple_radical_mul
  primeRotor finitePrimeEnsemble criticalMismatchParams criticalHeight
  IsCriticalZeroEnsemble critical_zero_iff critical_dagger layerScale
  criticalBalanceOk critical_balance_of_le_twenty
  RiemannAdmissibleBridge riemann_hypothesis_of_bridge
  critical_line_of_zero_ensemble)

end DstDiophantine
