import DstDiophantine.Gravity.ChiralSpectrum
import DstDiophantine.Algebra.Motor
import Mathlib.Analysis.Normed.Algebra.Exponential
import Mathlib.Analysis.SpecialFunctions.Trigonometric.Basic
import Mathlib.Tactic.Abel
import Mathlib.Tactic.Linarith
import Mathlib.Tactic.Module
import Mathlib.Tactic.NormNum
import Mathlib.Tactic.Ring

/-!
# Stabilizer of a chirality axis

## Paper boundary (do **not** claim)

A Weinberg angle, a V--A coupling, \(W/Z\) masses, and a chiral
\(\mathrm{SU}(2)_L\) gauge symmetry are **not** derived. The dual rotor moves
a fixed chirality axis. An abstract Lie-algebra isomorphism of the stabilizer
with \(\mathfrak{so}(2,1)\), beyond the bracket table in `ChiralSpectrum`, is
not formalised.

## What is proved

* A one-parameter group generated by a Cartan element fixes the axis. A dual
  rotation by angle \(\theta\) about \(B_{a+1}\) acts by
  \(e_a\mapsto\cos\theta\,e_a-\sin\theta\,e_{a+2}\), and about \(B_{a+2}\) by
  \(e_a\mapsto\cos\theta\,e_a+\sin\theta\,e_{a+1}\). At \(\theta=\pi\) the axis
  reverses and the projectors are exchanged. A boost of rapidity \(\alpha\)
  along the axis acts by \(e_a\mapsto\cosh\alpha\,e_a+\sinh\alpha\,e_0\), and that
  image squares to \(+1\).
* The parallel magnetic generator is a rotor. The parallel electric generator
  multiplies with its reverse to \(-1\), so it is not a rotor. In the neutral
  plane, \(c_B B_a + c_E E_a\) commutes with the axis if and only if
  \(c_E = 0\).
-/

namespace DstDiophantine

namespace Gravity

open PGA Generators Operations Logic LorentzLie Motor NormedSpace
open CliffordAlgebra (reverse)
open scoped Real

/-! ### Scalar products -/

private theorem smul_mul_smul (c d : ℝ) (x y : PGA) :
    (c • x) * (d • y) = (c * d) • (x * y) := by
  rw [smul_mul_assoc, mul_smul_comm, smul_smul]

private theorem exp_smul_mul_exp_neg (x : PGA) (t : ℝ) :
    exp (t • x) * exp ((-t) • x) = 1 := by
  have hc : Commute (t • x) ((-t) • x) :=
    ((Commute.refl x).smul_left t).smul_right (-t)
  have hball : ∀ y : PGA, y ∈ Metric.eball (0 : PGA) (expSeries ℝ PGA).radius := fun y =>
    (expSeries_radius_eq_top ℝ PGA).symm ▸ edist_lt_top _ _
  rw [← exp_add_of_commute_of_mem_ball hc (hball _) (hball _), ← add_smul,
    add_neg_cancel, zero_smul, exp_zero]

private theorem reverse_exp_smul_of_reverse_neg {k : PGA} (hk : reverse k = -k) (t : ℝ) :
    reverse (exp (t • k)) = exp ((-t) • k) := by
  have hrev : reverse (t • k) = -(t • k) := by
    rw [map_smul, hk, smul_neg]
  simpa [neg_smul] using reverse_exp_of_reverse_neg hrev

/-! ### Closed rotors -/

private theorem rotor_neg_unitary (k : PGA) (hk : k * k = -1) (φ : ℝ) :
    (Real.cos φ • (1 : PGA) + Real.sin φ • k) *
        (Real.cos φ • (1 : PGA) - Real.sin φ • k) = 1 := by
  have hsub : Real.cos φ • (1 : PGA) - Real.sin φ • k =
      Real.cos φ • (1 : PGA) + (-Real.sin φ) • k := by
    simp [sub_eq_add_neg, neg_smul]
  have hcross : Real.cos φ * -Real.sin φ + Real.sin φ * Real.cos φ = 0 := by ring
  have hpyth : Real.cos φ ^ 2 + Real.sin φ ^ 2 = 1 := Real.cos_sq_add_sin_sq φ
  trans (Real.cos φ ^ 2 + Real.sin φ ^ 2) • (1 : PGA) +
      (Real.cos φ * -Real.sin φ + Real.sin φ * Real.cos φ) • k
  · rw [hsub]
    simp only [mul_add, add_mul, smul_mul_smul, mul_one, one_mul, pow_two]
    rw [hk]
    abel_nf
    module
  · rw [hcross, zero_smul, add_zero, hpyth, one_smul]

private theorem rotor_pos_unitary (k : PGA) (hk : k * k = 1) (φ : ℝ) :
    (Real.cosh φ • (1 : PGA) + Real.sinh φ • k) *
        (Real.cosh φ • (1 : PGA) - Real.sinh φ • k) = 1 := by
  have hsub : Real.cosh φ • (1 : PGA) - Real.sinh φ • k =
      Real.cosh φ • (1 : PGA) + (-Real.sinh φ) • k := by
    simp [sub_eq_add_neg, neg_smul]
  have hcross : Real.cosh φ * -Real.sinh φ + Real.sinh φ * Real.cosh φ = 0 := by ring
  have hhyp : Real.cosh φ ^ 2 - Real.sinh φ ^ 2 = 1 := Real.cosh_sq_sub_sinh_sq φ
  trans (Real.cosh φ ^ 2 + -(Real.sinh φ ^ 2)) • (1 : PGA) +
      (Real.cosh φ * -Real.sinh φ + Real.sinh φ * Real.cosh φ) • k
  · rw [hsub]
    simp only [mul_add, add_mul, smul_mul_smul, mul_one, one_mul, pow_two]
    rw [hk]
    abel_nf
    module
  · rw [hcross, zero_smul, add_zero, ← sub_eq_add_neg, hhyp, one_smul]

private theorem rotor_neg_sq (k : PGA) (hk : k * k = -1) (φ : ℝ) :
    (Real.cos φ • (1 : PGA) + Real.sin φ • k) *
        (Real.cos φ • (1 : PGA) + Real.sin φ • k) =
      Real.cos (2 * φ) • (1 : PGA) + Real.sin (2 * φ) • k := by
  have hcos : Real.cos (2 * φ) = Real.cos φ ^ 2 - Real.sin φ ^ 2 := by
    rw [Real.cos_two_mul, Real.sin_sq, sub_eq_add_neg]
    ring
  have hsin : Real.sin (2 * φ) = 2 * Real.sin φ * Real.cos φ := Real.sin_two_mul φ
  trans (Real.cos φ ^ 2 - Real.sin φ ^ 2) • (1 : PGA) +
      (2 * Real.sin φ * Real.cos φ) • k
  · simp only [mul_add, add_mul, smul_mul_smul, mul_one, one_mul, pow_two]
    rw [hk]
    abel_nf
    module
  · rw [← hcos, ← hsin]

private theorem rotor_pos_sq (k : PGA) (hk : k * k = 1) (φ : ℝ) :
    (Real.cosh φ • (1 : PGA) + Real.sinh φ • k) *
        (Real.cosh φ • (1 : PGA) + Real.sinh φ • k) =
      Real.cosh (2 * φ) • (1 : PGA) + Real.sinh (2 * φ) • k := by
  have hcosh : Real.cosh (2 * φ) = Real.cosh φ ^ 2 + Real.sinh φ ^ 2 :=
    Real.cosh_two_mul φ
  have hsinh : Real.sinh (2 * φ) = 2 * Real.sinh φ * Real.cosh φ :=
    Real.sinh_two_mul φ
  trans (Real.cosh φ ^ 2 + Real.sinh φ ^ 2) • (1 : PGA) +
      (2 * Real.sinh φ * Real.cosh φ) • k
  · simp only [mul_add, add_mul, smul_mul_smul, mul_one, one_mul, pow_two]
    rw [hk]
    abel_nf
    module
  · rw [← hcosh, ← hsinh]

/-! ### Conjugation of an anticommuting axis -/

private theorem conj_anticomm_neg (k g : PGA) (hk : k * k = -1)
    (ha : k * g = -(g * k)) (φ : ℝ) :
    (Real.cos φ • (1 : PGA) + Real.sin φ • k) * g *
        (Real.cos φ • (1 : PGA) - Real.sin φ • k) =
      Real.cos (2 * φ) • g - Real.sin (2 * φ) • (g * k) := by
  set R : PGA := Real.cos φ • (1 : PGA) + Real.sin φ • k
  set Rv : PGA := Real.cos φ • (1 : PGA) - Real.sin φ • k
  have hpass : R * g = g * Rv := by
    have hkg : k * g = -(g * k) := ha
    calc (Real.cos φ • (1 : PGA) + Real.sin φ • k) * g
        = Real.cos φ • g + Real.sin φ • (k * g) := by
            simp [add_mul]
      _ = Real.cos φ • g + (-Real.sin φ) • (g * k) := by
            rw [hkg]; simp [smul_neg]
      _ = g * (Real.cos φ • (1 : PGA) + (-Real.sin φ) • k) := by
            simp [mul_add, mul_one]
      _ = g * Rv := by
            simp [Rv, sub_eq_add_neg, neg_smul]
  have hadd : R * g * Rv = (R * R) * g := by
    calc R * g * Rv = R * (g * Rv) := by rw [mul_assoc]
      _ = R * (R * g) := by rw [hpass]
      _ = (R * R) * g := by rw [← mul_assoc]
  rw [hadd]
  have hsq := rotor_neg_sq k hk φ
  calc (R * R) * g
      = (Real.cos (2 * φ) • (1 : PGA) + Real.sin (2 * φ) • k) * g := by rw [hsq]
    _ = Real.cos (2 * φ) • g + Real.sin (2 * φ) • (k * g) := by
          simp [add_mul]
    _ = Real.cos (2 * φ) • g + Real.sin (2 * φ) • (-(g * k)) := by rw [ha]
    _ = Real.cos (2 * φ) • g - Real.sin (2 * φ) • (g * k) := by
          simp [smul_neg, sub_eq_add_neg]

private theorem conj_anticomm_pos (k g : PGA) (hk : k * k = 1)
    (ha : k * g = -(g * k)) (φ : ℝ) :
    (Real.cosh φ • (1 : PGA) + Real.sinh φ • k) * g *
        (Real.cosh φ • (1 : PGA) - Real.sinh φ • k) =
      Real.cosh (2 * φ) • g + Real.sinh (2 * φ) • (k * g) := by
  set R : PGA := Real.cosh φ • (1 : PGA) + Real.sinh φ • k
  set Rv : PGA := Real.cosh φ • (1 : PGA) - Real.sinh φ • k
  have hpass : R * g = g * Rv := by
    calc (Real.cosh φ • (1 : PGA) + Real.sinh φ • k) * g
        = Real.cosh φ • g + Real.sinh φ • (k * g) := by
            simp [add_mul]
      _ = Real.cosh φ • g + (-Real.sinh φ) • (g * k) := by
            rw [ha]; simp [smul_neg]
      _ = g * (Real.cosh φ • (1 : PGA) + (-Real.sinh φ) • k) := by
            simp [mul_add, mul_one]
      _ = g * Rv := by
            simp [Rv, sub_eq_add_neg, neg_smul]
  calc R * g * Rv
      = R * (R * g) := by rw [mul_assoc, hpass]
    _ = (R * R) * g := by rw [← mul_assoc]
    _ = (Real.cosh (2 * φ) • (1 : PGA) + Real.sinh (2 * φ) • k) * g := by
          rw [rotor_pos_sq k hk φ]
    _ = Real.cosh (2 * φ) • g + Real.sinh (2 * φ) • (k * g) := by
          simp [add_mul]

/-! ### Fixing an axis that commutes with the generator -/

private theorem commute_closed_rotor_neg {k g : PGA} (hc : Commute k g) (φ : ℝ) :
    Commute (Real.cos φ • (1 : PGA) + Real.sin φ • k) g :=
  ((Commute.one_left g).smul_left (Real.cos φ)).add_left (hc.smul_left (Real.sin φ))

private theorem commute_closed_rotor_pos {k g : PGA} (hc : Commute k g) (φ : ℝ) :
    Commute (Real.cosh φ • (1 : PGA) + Real.sinh φ • k) g :=
  ((Commute.one_left g).smul_left (Real.cosh φ)).add_left (hc.smul_left (Real.sinh φ))

private theorem conj_comm_neg (k g : PGA) (hk : k * k = -1) (hc : Commute k g) (φ : ℝ) :
    (Real.cos φ • (1 : PGA) + Real.sin φ • k) * g *
        (Real.cos φ • (1 : PGA) - Real.sin φ • k) = g := by
  have hR := commute_closed_rotor_neg hc φ
  calc (Real.cos φ • (1 : PGA) + Real.sin φ • k) * g *
          (Real.cos φ • (1 : PGA) - Real.sin φ • k)
      = g * ((Real.cos φ • (1 : PGA) + Real.sin φ • k) *
          (Real.cos φ • (1 : PGA) - Real.sin φ • k)) := by
          rw [← mul_assoc, hR.eq]
    _ = g * 1 := by rw [rotor_neg_unitary k hk φ]
    _ = g := by rw [mul_one]

private theorem conj_comm_pos (k g : PGA) (hk : k * k = 1) (hc : Commute k g) (φ : ℝ) :
    (Real.cosh φ • (1 : PGA) + Real.sinh φ • k) * g *
        (Real.cosh φ • (1 : PGA) - Real.sinh φ • k) = g := by
  have hR := commute_closed_rotor_pos hc φ
  calc (Real.cosh φ • (1 : PGA) + Real.sinh φ • k) * g *
          (Real.cosh φ • (1 : PGA) - Real.sinh φ • k)
      = g * ((Real.cosh φ • (1 : PGA) + Real.sinh φ • k) *
          (Real.cosh φ • (1 : PGA) - Real.sinh φ • k)) := by
          rw [← mul_assoc, hR.eq]
    _ = g * 1 := by rw [rotor_pos_unitary k hk φ]
    _ = g := by rw [mul_one]

/-! ### Products of the axis with the charged generators -/

theorem spatialGen_mul_cyclic_succ (a : Fin 3) :
    spatialGen a * cyclic (a + 1) = spatialGen (a + 2) := by
  match a with
  | 0 =>
      rw [show (0 + 1 : Fin 3) = 1 by decide, show (0 + 2 : Fin 3) = 2 by decide]
      simp only [spatialGen, cyclic]
      rw [← mul_assoc, e1_sq, one_mul]
  | 1 =>
      rw [show (1 + 1 : Fin 3) = 2 by decide, show (1 + 2 : Fin 3) = 0 by decide]
      have h2 : ι 2 * ι 2 = (1 : PGA) := by
        simpa [Q311_e5vec, w311] using e_sq (2 : Fin 5)
      simp only [spatialGen, cyclic]
      rw [← mul_assoc, h2, one_mul]
  | 2 =>
      rw [show (2 + 1 : Fin 3) = 0 by decide, show (2 + 2 : Fin 3) = 1 by decide]
      have h3 : ι 3 * ι 3 = (1 : PGA) := by
        simpa [Q311_e5vec, w311] using e_sq (3 : Fin 5)
      simp only [spatialGen, cyclic]
      rw [← mul_assoc, h3, one_mul]

theorem spatialGen_mul_cyclic_succ_succ (a : Fin 3) :
    spatialGen a * cyclic (a + 2) = -spatialGen (a + 1) := by
  match a with
  | 0 =>
      rw [show (0 + 2 : Fin 3) = 2 by decide, show (0 + 1 : Fin 3) = 1 by decide]
      simp only [spatialGen, cyclic]
      have hanti : ι 1 * ι 2 = -(ι 2 * ι 1) := e_mul_anticomm (by decide)
      calc ι 1 * (ι 2 * ι 1)
          = (ι 1 * ι 2) * ι 1 := by rw [← mul_assoc]
        _ = (-(ι 2 * ι 1)) * ι 1 := by rw [hanti]
        _ = -(ι 2 * (ι 1 * ι 1)) := by simp [mul_assoc]
        _ = -(ι 2) := by simp [e1_sq]
  | 1 =>
      rw [show (1 + 2 : Fin 3) = 0 by decide, show (1 + 1 : Fin 3) = 2 by decide]
      have h2 : ι 2 * ι 2 = (1 : PGA) := by
        simpa [Q311_e5vec, w311] using e_sq (2 : Fin 5)
      simp only [spatialGen, cyclic]
      have hanti : ι 2 * ι 3 = -(ι 3 * ι 2) := e_mul_anticomm (by decide)
      calc ι 2 * (ι 3 * ι 2)
          = (ι 2 * ι 3) * ι 2 := by rw [← mul_assoc]
        _ = (-(ι 3 * ι 2)) * ι 2 := by rw [hanti]
        _ = -(ι 3 * (ι 2 * ι 2)) := by simp [mul_assoc]
        _ = -(ι 3) := by simp [h2]
  | 2 =>
      rw [show (2 + 2 : Fin 3) = 1 by decide, show (2 + 1 : Fin 3) = 0 by decide]
      have h3 : ι 3 * ι 3 = (1 : PGA) := by
        simpa [Q311_e5vec, w311] using e_sq (3 : Fin 5)
      simp only [spatialGen, cyclic]
      have hanti : ι 3 * ι 1 = -(ι 1 * ι 3) := e_mul_anticomm (by decide)
      calc ι 3 * (ι 1 * ι 3)
          = (ι 3 * ι 1) * ι 3 := by rw [← mul_assoc]
        _ = (-(ι 1 * ι 3)) * ι 3 := by rw [hanti]
        _ = -(ι 1 * (ι 3 * ι 3)) := by simp [mul_assoc]
        _ = -(ι 1) := by simp [h3]

theorem hyperbolic_mul_spatialGen (a : Fin 3) :
    hyperbolic a * spatialGen a = ι 0 := by
  fin_cases a
  · simp only [hyperbolic, spatialGen]
    rw [mul_assoc, e1_sq, mul_one]
  · have h2 : ι 2 * ι 2 = (1 : PGA) := by
      simpa [Q311_e5vec, w311] using e_sq (2 : Fin 5)
    simp only [hyperbolic, spatialGen]
    rw [mul_assoc, h2, mul_one]
  · have h3 : ι 3 * ι 3 = (1 : PGA) := by
      simpa [Q311_e5vec, w311] using e_sq (3 : Fin 5)
    simp only [hyperbolic, spatialGen]
    rw [mul_assoc, h3, mul_one]

theorem charged_mul_spatialGen (a : Fin 3) :
    chargedGen a 0 * spatialGen a = ι 0 ∧
      chargedGen a 1 * spatialGen a = -spatialGen (a + 2) ∧
        chargedGen a 2 * spatialGen a = spatialGen (a + 1) := by
  refine ⟨?_, ?_, ?_⟩
  · simpa [chargedGen] using hyperbolic_mul_spatialGen a
  · have hanti := chargedGen_anticomm_axis a 1
    calc chargedGen a 1 * spatialGen a
        = -(-(chargedGen a 1 * spatialGen a)) := by simp
      _ = -(spatialGen a * chargedGen a 1) := by rw [← hanti]
      _ = -(spatialGen a * cyclic (a + 1)) := by simp [chargedGen]
      _ = -spatialGen (a + 2) := by rw [spatialGen_mul_cyclic_succ]
  · have hanti := chargedGen_anticomm_axis a 2
    calc chargedGen a 2 * spatialGen a
        = -(-(chargedGen a 2 * spatialGen a)) := by simp
      _ = -(spatialGen a * chargedGen a 2) := by rw [← hanti]
      _ = -(spatialGen a * cyclic (a + 2)) := by simp [chargedGen]
      _ = -(-spatialGen (a + 1)) := by rw [spatialGen_mul_cyclic_succ_succ]
      _ = spatialGen (a + 1) := by simp

/-! ### Cartan groups fix the axis; charged groups move it -/

private theorem exp_neg_closed_neg (k : PGA) (hk : k * k = -1) (t : ℝ) :
    exp ((-t) • k) = Real.cos t • (1 : PGA) - Real.sin t • k := by
  rw [exp_of_sq_neg_one hk]
  simp [Real.cos_neg, Real.sin_neg, sub_eq_add_neg]

private theorem exp_neg_closed_pos (k : PGA) (hk : k * k = 1) (t : ℝ) :
    exp ((-t) • k) = Real.cosh t • (1 : PGA) - Real.sinh t • k := by
  rw [exp_of_sq_one hk]
  simp [Real.cosh_neg, Real.sinh_neg, sub_eq_add_neg]

theorem cartan_rotation_fixes_axis (a : Fin 3) (t : ℝ) :
    exp (t • cyclic a) * spatialGen a * reverse (exp (t • cyclic a)) =
      spatialGen a := by
  have hc : Commute (cyclic a) (spatialGen a) :=
    (cartanGen_commute_axis a 0).symm
  rw [reverse_exp_smul_of_reverse_neg (cyclic_reverse a),
    exp_of_sq_neg_one (cyclic_sq a),
    exp_neg_closed_neg (cyclic a) (cyclic_sq a)]
  exact conj_comm_neg (cyclic a) (spatialGen a) (cyclic_sq a) hc t

theorem cartan_boost_fixes_axis (a : Fin 3) (t : ℝ) :
    exp (t • hyperbolic (a + 1)) * spatialGen a *
        reverse (exp (t • hyperbolic (a + 1))) = spatialGen a ∧
      exp (t • hyperbolic (a + 2)) * spatialGen a *
        reverse (exp (t • hyperbolic (a + 2))) = spatialGen a := by
  have hc1 : Commute (hyperbolic (a + 1)) (spatialGen a) := by
    simpa [cartanGen] using (cartanGen_commute_axis a 1).symm
  have hc2 : Commute (hyperbolic (a + 2)) (spatialGen a) := by
    simpa [cartanGen] using (cartanGen_commute_axis a 2).symm
  refine ⟨?_, ?_⟩
  · rw [reverse_exp_smul_of_reverse_neg (hyperbolic_reverse (a + 1)),
      exp_of_sq_one (hyperbolic_sq (a + 1)),
      exp_neg_closed_pos (hyperbolic (a + 1)) (hyperbolic_sq (a + 1))]
    exact conj_comm_pos (hyperbolic (a + 1)) (spatialGen a)
      (hyperbolic_sq (a + 1)) hc1 t
  · rw [reverse_exp_smul_of_reverse_neg (hyperbolic_reverse (a + 2)),
      exp_of_sq_one (hyperbolic_sq (a + 2)),
      exp_neg_closed_pos (hyperbolic (a + 2)) (hyperbolic_sq (a + 2))]
    exact conj_comm_pos (hyperbolic (a + 2)) (spatialGen a)
      (hyperbolic_sq (a + 2)) hc2 t

/-- Dual rotation by angle `θ` about `B_{a+1}` turns the chirality axis in the
plane of `e_a` and `e_{a+2}`. -/
theorem dualRotation_succ_axis (a : Fin 3) (θ : ℝ) :
    exp ((θ / 2) • cyclic (a + 1)) * spatialGen a *
        reverse (exp ((θ / 2) • cyclic (a + 1))) =
      Real.cos θ • spatialGen a - Real.sin θ • spatialGen (a + 2) := by
  have ha : cyclic (a + 1) * spatialGen a =
      -(spatialGen a * cyclic (a + 1)) := by
    calc cyclic (a + 1) * spatialGen a
        = chargedGen a 1 * spatialGen a := by simp [chargedGen]
      _ = -spatialGen (a + 2) := (charged_mul_spatialGen a).2.1
      _ = -(spatialGen a * cyclic (a + 1)) := by rw [← spatialGen_mul_cyclic_succ]
  rw [reverse_exp_smul_of_reverse_neg (cyclic_reverse (a + 1)),
    exp_of_sq_neg_one (cyclic_sq (a + 1)),
    exp_neg_closed_neg (cyclic (a + 1)) (cyclic_sq (a + 1))]
  have hdouble : 2 * (θ / 2) = θ := by ring
  rw [conj_anticomm_neg (cyclic (a + 1)) (spatialGen a) (cyclic_sq (a + 1)) ha (θ / 2),
    hdouble, spatialGen_mul_cyclic_succ]

/-- Dual rotation by angle `θ` about `B_{a+2}` turns the axis into `e_{a+1}`. -/
theorem dualRotation_succ_succ_axis (a : Fin 3) (θ : ℝ) :
    exp ((θ / 2) • cyclic (a + 2)) * spatialGen a *
        reverse (exp ((θ / 2) • cyclic (a + 2))) =
      Real.cos θ • spatialGen a + Real.sin θ • spatialGen (a + 1) := by
  have ha : cyclic (a + 2) * spatialGen a =
      -(spatialGen a * cyclic (a + 2)) := by
    calc cyclic (a + 2) * spatialGen a
        = chargedGen a 2 * spatialGen a := by simp [chargedGen]
      _ = spatialGen (a + 1) := (charged_mul_spatialGen a).2.2
      _ = -(-spatialGen (a + 1)) := by simp
      _ = -(spatialGen a * cyclic (a + 2)) := by rw [← spatialGen_mul_cyclic_succ_succ]
  rw [reverse_exp_smul_of_reverse_neg (cyclic_reverse (a + 2)),
    exp_of_sq_neg_one (cyclic_sq (a + 2)),
    exp_neg_closed_neg (cyclic (a + 2)) (cyclic_sq (a + 2))]
  have hdouble : 2 * (θ / 2) = θ := by ring
  rw [conj_anticomm_neg (cyclic (a + 2)) (spatialGen a) (cyclic_sq (a + 2)) ha (θ / 2),
    hdouble, spatialGen_mul_cyclic_succ_succ]
  simp [sub_eq_add_neg, smul_neg, neg_neg]

/-- At angle `π` the perpendicular dual rotation reverses the axis. -/
theorem dualRotation_pi_axis (a : Fin 3) :
    exp ((Real.pi / 2) • cyclic (a + 1)) * spatialGen a *
        reverse (exp ((Real.pi / 2) • cyclic (a + 1))) =
      -spatialGen a := by
  rw [dualRotation_succ_axis a Real.pi, Real.cos_pi, Real.sin_pi]
  simp [zero_smul]

/-- The same half-turn exchanges the two projectors. -/
theorem dualRotation_exchanges_projectors (a : Fin 3) :
    exp ((Real.pi / 2) • cyclic (a + 1)) * chiralityRAxis a *
        reverse (exp ((Real.pi / 2) • cyclic (a + 1))) =
      chiralityLAxis a := by
  set R : PGA := exp ((Real.pi / 2) • cyclic (a + 1))
  have hunit : R * reverse R = 1 := by
    rw [reverse_exp_smul_of_reverse_neg (cyclic_reverse (a + 1))]
    exact exp_smul_mul_exp_neg (cyclic (a + 1)) (Real.pi / 2)
  have haxis : R * spatialGen a * reverse R = -spatialGen a :=
    dualRotation_pi_axis a
  calc R * (((1 : PGA) + spatialGen a) * half) * reverse R
      = R * ((1 : PGA) + spatialGen a) * (half * reverse R) := by simp [mul_assoc]
    _ = R * ((1 : PGA) + spatialGen a) * (reverse R * half) := by rw [half_comm]
    _ = R * ((1 : PGA) + spatialGen a) * reverse R * half := by simp [mul_assoc]
    _ = (R * reverse R + R * spatialGen a * reverse R) * half := by
          simp [mul_add, add_mul, mul_one]
    _ = (1 + -spatialGen a) * half := by rw [hunit, haxis]
    _ = chiralityLAxis a := by simp [chiralityLAxis, sub_eq_add_neg]

/-- A boost of rapidity `α` along the axis tilts it into time. -/
theorem boost_along_axis (a : Fin 3) (α : ℝ) :
    exp ((α / 2) • hyperbolic a) * spatialGen a *
        reverse (exp ((α / 2) • hyperbolic a)) =
      Real.cosh α • spatialGen a + Real.sinh α • ι 0 := by
  have ha : hyperbolic a * spatialGen a =
      -(spatialGen a * hyperbolic a) := by
    have hanti := chargedGen_anticomm_axis a 0
    calc hyperbolic a * spatialGen a
        = chargedGen a 0 * spatialGen a := by simp [chargedGen]
      _ = -(-(chargedGen a 0 * spatialGen a)) := by simp
      _ = -(spatialGen a * chargedGen a 0) := by rw [← hanti]
      _ = -(spatialGen a * hyperbolic a) := by simp [chargedGen]
  rw [reverse_exp_smul_of_reverse_neg (hyperbolic_reverse a),
    exp_of_sq_one (hyperbolic_sq a),
    exp_neg_closed_pos (hyperbolic a) (hyperbolic_sq a)]
  have hdouble : 2 * (α / 2) = α := by ring
  rw [conj_anticomm_pos (hyperbolic a) (spatialGen a) (hyperbolic_sq a) ha (α / 2),
    hdouble, hyperbolic_mul_spatialGen]

/-- The boosted axis still squares to `+1`. -/
theorem boosted_axis_sq (a : Fin 3) (α : ℝ) :
    (Real.cosh α • spatialGen a + Real.sinh α • ι 0) *
        (Real.cosh α • spatialGen a + Real.sinh α • ι 0) = 1 := by
  have hboost := boost_along_axis a α
  set R : PGA := exp ((α / 2) • hyperbolic a)
  have hunit : R * reverse R = 1 := by
    rw [reverse_exp_smul_of_reverse_neg (hyperbolic_reverse a)]
    exact exp_smul_mul_exp_neg (hyperbolic a) (α / 2)
  have hunitR : reverse R * R = 1 := reverse_mul_of_mul_reverse hunit
  rw [← hboost]
  calc (R * spatialGen a * reverse R) * (R * spatialGen a * reverse R)
      = R * spatialGen a * (reverse R * (R * spatialGen a * reverse R)) := by
          simp [mul_assoc]
    _ = R * spatialGen a * ((reverse R * R) * spatialGen a * reverse R) := by
          simp [mul_assoc]
    _ = R * spatialGen a * (spatialGen a * reverse R) := by
          rw [hunitR, one_mul]
    _ = R * (spatialGen a * spatialGen a) * reverse R := by
          simp [mul_assoc]
    _ = R * reverse R := by rw [spatialGen_sq, mul_one]
    _ = 1 := hunit


/-- The parallel magnetic generator is a rotor; the parallel electric generator
squares with its reverse to `-1`. -/
theorem cyclic_is_rotor (a : Fin 3) :
    cyclic a * reverse (cyclic a) = 1 := by
  rw [cyclic_reverse, mul_neg, cyclic_sq]
  simp

theorem hyperbolic_reverse_mul (a : Fin 3) :
    hyperbolic a * reverse (hyperbolic a) = -1 := by
  rw [hyperbolic_reverse, mul_neg, hyperbolic_sq]

/-! ### The stabilizer is the Cartan span -/

private theorem commutator_chargedGen_axis (a i : Fin 3) :
    Generators.commutator (chargedGen a i) (spatialGen a) =
      (2 : ℝ) • (chargedGen a i * spatialGen a) := by
  have hanti := chargedGen_anticomm_axis a i
  calc Generators.commutator (chargedGen a i) (spatialGen a)
      = chargedGen a i * spatialGen a - spatialGen a * chargedGen a i := by
          rfl
    _ = chargedGen a i * spatialGen a - -(chargedGen a i * spatialGen a) := by
          rw [hanti]
    _ = (2 : ℝ) • (chargedGen a i * spatialGen a) := by
          simp [sub_eq_add_neg, neg_neg, two_smul]

/-- In the neutral plane of one axis, only the magnetic generator preserves
the chirality axis. -/
theorem commute_neutral_axis_iff (a : Fin 3) (cB cE : ℝ) :
    Commute (spatialGen a) (cB • cyclic a + cE • hyperbolic a) ↔ cE = 0 := by
  constructor
  · intro h
    have h0 : Generators.commutator (cB • cyclic a + cE • hyperbolic a) (spatialGen a) = 0 := by
      rw [Generators.commutator, h.eq, sub_self]
    have hcyc : Generators.commutator (cyclic a) (spatialGen a) = 0 := by
      have heq : cyclic a * spatialGen a = spatialGen a * cyclic a := by
        simpa [cartanGen] using (cartanGen_commute_axis a 0).symm.eq
      rw [Generators.commutator, heq, sub_self]
    have hhyp : Generators.commutator (hyperbolic a) (spatialGen a) = (2 : ℝ) • ι 0 := by
      simpa [chargedGen, hyperbolic_mul_spatialGen] using commutator_chargedGen_axis a 0
    have hlin : cE • ((2 : ℝ) • ι 0) = 0 := by
      simp only [commutator_add_left, commutator_smul_left, hcyc, hhyp,
        smul_zero, zero_add] at h0
      exact h0
    have hsmul : ((2 : ℝ) * cE) • ι 0 = 0 := by
      simpa [smul_smul, mul_comm] using hlin
    have hι : ι 0 ≠ 0 := by
      intro hz
      have : algebraMap ℝ PGA (-1) = 0 := by rw [← e0_sq, hz, mul_zero]
      have hℝ : (-1 : ℝ) = 0 :=
        (FaithfulSMul.algebraMap_eq_zero_iff (R := ℝ) (A := PGA)).mp this
      norm_num at hℝ
    have h2 : (2 : ℝ) * cE = 0 := (smul_eq_zero.mp hsmul).resolve_right hι
    exact (mul_eq_zero.mp h2).resolve_left (by norm_num)
  · intro hcE
    have hc : Commute (spatialGen a) (cB • cyclic a) := by
      simpa [cartanGen] using (cartanGen_commute_axis a 0).smul_right cB
    simpa [hcE, zero_smul, add_zero] using hc

end Gravity

end DstDiophantine
